spring.application.name=viagens

spring.datasource.url=jdbc:postgresql://127.0.0.1:5434/viagens_db
spring.datasource.username=viagens_user
spring.datasource.password=viagens123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect